floors: 3
max_people_floor: 12
steps: 20000
visualisation: true
elevators:
- max_people: 5
  speed: 5
  starting_floor: 0
algorithm: nearest_car
model: null
traffic:
  generator_type: 'from file'
  intensity: 0.55000000000000002
  seed: null
  up_peak_params:
    arrival_floor: 0
    destination_distribution: null
  down_peak_params: null
  interfloor_params: null
  mixed_peak_params: null
  uniform_params: null
  from_file_params:
    filename: 'test.csv'
