floors: 10
max_people_floor: 12
steps: 86400
visualisation: false
elevators:
- max_people: 5
  speed: 5
  starting_floor: 0
- max_people: 5
  speed: 5
  starting_floor: 0
- max_people: 5
  speed: 5
  starting_floor: 0
algorithm: collective_control
model: null
traffic:
  generator_type: up-peak
  intensity: 0.09
  seed: null
  up_peak_params:
    arrival_floor: 0
    destination_distribution: null
  down_peak_params: null
  interfloor_params: null
  mixed_peak_params: null
  uniform_params: null
  from_file_params: null
